### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by z0rielle** [BlueFrog130/Minecraft-KillCounter#17]
For MCBE 1.20.80/81

**Comment by BlueFrog130** [comment]
I will need to rewrite the entire thing to use the new game test framework rather than the deprecated scripting framework

**Comment by z0rielle** [comment]
Please

**Comment by BlueFrog130** [comment]
> Please

I will look into it this week

**Comment by BlueFrog130** [comment]
@mioscape 

I updated the addon to use the latest minecraft version. You can install the behavior pack and it will work as described in the guide.

[v3 Release](https://github.com/BlueFrogGames/Minecraft-KillCounter/releases/tag/3.0.0)
